spring:
  application:
    name: im-server

im:
  server:
    port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true

server:
  port: 8080
  connection-timeout: 60s

management:
  endpoints:
   web:
    exposure:
     include: '*'

